from src.components.prompt_manager import PromptManager
from src.components.llm_client import LLMClient

import json

class BusinessAdvisor:
    """
    Orchestrates AI-powered business advisory services.
    """

    def __init__(self):
        """
        Initializes the Business Advisor.
        """

        self.prompt_manager = PromptManager()
        self.llm_client = LLMClient()


    def _generate_response(
        self,
        prompt: str
    ):
        """
        Generates an AI response for the supplied prompt.

        Parameters
        ----------
        prompt : str
            Prompt to send to the LLM.

        Returns
        -------
        dict
            Response generated by the LLM.
        """

        return self.llm_client.generate_response(prompt)    


    def generate_summary(
        self,
        business_context: dict
    ):
        """
        Generates an executive summary.

        Parameters
        ----------
        business_context : dict
            Operational Intelligence output.

        Returns
        -------
        dict
            AI-generated executive summary.
        """

        prompt = self.prompt_manager.get_summary_prompt(
            business_context
        )

        return self._generate_response(prompt) 
    

    def explain_prediction(
        self,
        business_context: dict,
        manager_query: str
    ):
        """
        Generates an explanation for the business forecast.

        Parameters
        ----------
        business_context : dict
            Operational Intelligence output.

        manager_query : str
            Manager's question.

        Returns
        -------
        dict
            AI-generated explanation.
        """

        prompt = self.prompt_manager.get_explanation_prompt(
            business_context,
            manager_query
        )

        return self._generate_response(prompt)
    

    def generate_recommendations(
        self,
        business_context: dict
    ):
        """
        Generates operational recommendations.

        Parameters
        ----------
        business_context : dict
            Operational Intelligence output.

        Returns
        -------
        dict
            AI-generated recommendations.
        """

        prompt = self.prompt_manager.get_recommendation_prompt(
            business_context
        )

        return self._generate_response(prompt)
    

    def answer_question(
        self,
        business_context: dict,
        manager_query: str
    ):
        """
        Answers a manager's business question.

        Parameters
        ----------
        business_context : dict
            Operational Intelligence output.

        manager_query : str
            Manager's question.

        Returns
        -------
        dict
            AI-generated response.
        """

        prompt = self.prompt_manager.get_chat_prompt(
            business_context,
            manager_query
        )

        return self._generate_response(prompt)
    

    def generate_weekly_summary(
        self,
        business_context: dict
    ):
        """
        Generates a weekly business summary.

        Parameters
        ----------
        business_context : dict
            Weekly forecast context.

        Returns
        -------
        dict
            AI-generated weekly summary.
        """

        prompt = self.prompt_manager.get_weekly_summary_prompt(
            business_context
        )

        return self._generate_response(prompt)
    

    def explain_recursive_forecast(
        self,
        business_context: dict
    ):
        """
        Explains recursive forecasting results.

        Parameters
        ----------
        business_context : dict
            Recursive forecast context.

        Returns
        -------
        dict
            AI-generated explanation.
        """

        prompt = self.prompt_manager.get_recursive_forecast_prompt(
            business_context
        )

        return self._generate_response(prompt)
    

    def simulate_scenario(
        self,
        original_context: dict,
        simulated_context: dict,
        manager_query: str
    ):
        """
        Explains simulated business scenarios.

        Parameters
        ----------
        original_context : dict
            Original business context.

        simulated_context : dict
            Simulated business context.

        manager_query : str
            Manager's scenario question.

        Returns
        -------
        dict
            AI-generated scenario analysis.
        """

        prompt = self.prompt_manager.get_scenario_simulation_prompt(
            original_context,
            simulated_context,
            manager_query
        )

        return self._generate_response(prompt)
    

    def generate_report(
        self,
        business_context: dict
    ):
        """
        Generates a business report.

        Parameters
        ----------
        business_context : dict
            Operational Intelligence output.

        Returns
        -------
        dict
            AI-generated report.
        """

        prompt = self.prompt_manager.get_report_prompt(
            business_context
        )

        return self._generate_response(prompt)
    

    def parse_prediction_request(
        self,
        manager_request: str
    ):
        """
        Converts a natural language business request into
        a structured prediction request.

        Parameters
        ----------
        manager_request : str
            User's prediction request.

        Returns
        -------
        dict
            Structured business request.
        """

        prompt = (
            self.prompt_manager.get_prediction_request_prompt(
                manager_request
            )
        )

        response = self._generate_response(
            prompt
        )

        business_request = json.loads(
            response["response"]
        )

        return business_request

